sudo: required
language: python
python: "3.7"

jobs:
  include:
    - name: "tests"
      script:
        - cd tests
        - python -m unittest test_module.poker_logic_test

notifications:
    email: false
