sudo: required
language: python
python: "3.7"

jobs:
  include:
    - name: "tests"
      script:
        - cd tests
        - python poker_logic_test.py --cov=core .

notifications:
    email: false
