sudo: required
language: python
python: "3.7"

jobs:
  include:
    - name: "tests"
      script:
        - cd tests
        - python networks_work_test.py
        - python poker_logic_test.py

notifications:
    email: false
