os: linux
sudo: required
language: python
python: "3.7"

#install:
#    - pip install -r requirements.txt
jobs:
  include:
    - name: "tests"
      script:
        - python course_work/tests/poker_logic_test.py
        - python course_work/tests/network_work_test.py

notifications:
    email: false
