# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Anton\PycharmProjects\course_work\uis\poker_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 854)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SettingsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.SettingsBox.setGeometry(QtCore.QRect(60, 590, 201, 171))
        self.SettingsBox.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.SettingsBox.setObjectName("SettingsBox")
        self.ReportBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ReportBox.setGeometry(QtCore.QRect(760, 590, 191, 171))
        self.ReportBox.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.ReportBox.setObjectName("ReportBox")
        self.ReportText = QtWidgets.QListView(self.ReportBox)
        self.ReportText.setGeometry(QtCore.QRect(20, 30, 151, 121))
        self.ReportText.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.ReportText.setObjectName("ReportText")
        self.ActionsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ActionsBox.setGeometry(QtCore.QRect(290, 590, 431, 171))
        self.ActionsBox.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.ActionsBox.setObjectName("ActionsBox")
        self.PassButton = QtWidgets.QPushButton(self.ActionsBox)
        self.PassButton.setGeometry(QtCore.QRect(30, 40, 75, 31))
        self.PassButton.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"font: 900 12pt \"Perpetua Titling MT\";\n"
"color: rgb(0, 0, 0);")
        self.PassButton.setObjectName("PassButton")
        self.CheckButton = QtWidgets.QPushButton(self.ActionsBox)
        self.CheckButton.setGeometry(QtCore.QRect(130, 40, 75, 31))
        self.CheckButton.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"font: 900 12pt \"Perpetua Titling MT\";\n"
"color: rgb(0, 0, 0);")
        self.CheckButton.setObjectName("CheckButton")
        self.CallButton = QtWidgets.QPushButton(self.ActionsBox)
        self.CallButton.setGeometry(QtCore.QRect(230, 40, 75, 31))
        self.CallButton.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"font: 900 12pt \"Perpetua Titling MT\";\n"
"color: rgb(0, 0, 0);")
        self.CallButton.setObjectName("CallButton")
        self.RaiseButton = QtWidgets.QPushButton(self.ActionsBox)
        self.RaiseButton.setGeometry(QtCore.QRect(330, 40, 71, 31))
        self.RaiseButton.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"font: 900 12pt \"Perpetua Titling MT\";\n"
"color: rgb(0, 0, 0);")
        self.RaiseButton.setObjectName("RaiseButton")
        self.RaiseValuSlider = QtWidgets.QSlider(self.ActionsBox)
        self.RaiseValuSlider.setGeometry(QtCore.QRect(120, 130, 181, 22))
        self.RaiseValuSlider.setStyleSheet("border: 2px solid grey;\n"
"background-color: rgb(232, 232, 232);")
        self.RaiseValuSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RaiseValuSlider.setObjectName("RaiseValuSlider")
        self.RaiseValue = QtWidgets.QLabel(self.ActionsBox)
        self.RaiseValue.setGeometry(QtCore.QRect(240, 90, 51, 31))
        self.RaiseValue.setStyleSheet("border: 2px solid grey;\n"
"background-color: rgb(232, 232, 232);")
        self.RaiseValue.setText("")
        self.RaiseValue.setObjectName("RaiseValue")
        self.RaiseText = QtWidgets.QLabel(self.ActionsBox)
        self.RaiseText.setGeometry(QtCore.QRect(140, 100, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.RaiseText.setFont(font)
        self.RaiseText.setStyleSheet("font: 900 12pt \"Perpetua Titling MT\";")
        self.RaiseText.setObjectName("RaiseText")
        self.PokerTableImage = QtWidgets.QLabel(self.centralwidget)
        self.PokerTableImage.setGeometry(QtCore.QRect(0, 0, 1001, 871))
        self.PokerTableImage.setText("")
        self.PokerTableImage.setPixmap(QtGui.QPixmap("C:\\Users\\Anton\\PycharmProjects\\course_work\\uis\\../images/Poker_table_picture_full.png"))
        self.PokerTableImage.setObjectName("PokerTableImage")
        self.BoardBox = QtWidgets.QGroupBox(self.centralwidget)
        self.BoardBox.setGeometry(QtCore.QRect(390, 250, 211, 81))
        self.BoardBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.BoardBox.setObjectName("BoardBox")
        self.widget = QtWidgets.QWidget(self.BoardBox)
        self.widget.setGeometry(QtCore.QRect(10, 20, 191, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.card1_board = QtWidgets.QLabel(self.widget)
        self.card1_board.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"background-color: rgb(0, 0, 98);")
        self.card1_board.setText("")
        self.card1_board.setObjectName("card1_board")
        self.horizontalLayout.addWidget(self.card1_board)
        self.card2_board = QtWidgets.QLabel(self.widget)
        self.card2_board.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"background-color: rgb(0, 0, 98);")
        self.card2_board.setText("")
        self.card2_board.setObjectName("card2_board")
        self.horizontalLayout.addWidget(self.card2_board)
        self.card3_board = QtWidgets.QLabel(self.widget)
        self.card3_board.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"background-color: rgb(0, 0, 98);")
        self.card3_board.setText("")
        self.card3_board.setObjectName("card3_board")
        self.horizontalLayout.addWidget(self.card3_board)
        self.card4_board = QtWidgets.QLabel(self.widget)
        self.card4_board.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"background-color: rgb(0, 0, 98);")
        self.card4_board.setText("")
        self.card4_board.setObjectName("card4_board")
        self.horizontalLayout.addWidget(self.card4_board)
        self.card5_board = QtWidgets.QLabel(self.widget)
        self.card5_board.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"background-color: rgb(0, 0, 98);")
        self.card5_board.setText("")
        self.card5_board.setObjectName("card5_board")
        self.horizontalLayout.addWidget(self.card5_board)
        self.Hand2Box = QtWidgets.QGroupBox(self.centralwidget)
        self.Hand2Box.setGeometry(QtCore.QRect(450, 350, 91, 81))
        self.Hand2Box.setStyleSheet("color: rgb(255, 255, 255);")
        self.Hand2Box.setObjectName("Hand2Box")
        self.widget1 = QtWidgets.QWidget(self.Hand2Box)
        self.widget1.setGeometry(QtCore.QRect(10, 20, 71, 51))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.card1_hand2 = QtWidgets.QLabel(self.widget1)
        self.card1_hand2.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"background-color: rgb(0, 0, 98);")
        self.card1_hand2.setText("")
        self.card1_hand2.setObjectName("card1_hand2")
        self.horizontalLayout_2.addWidget(self.card1_hand2)
        self.card2_hand2 = QtWidgets.QLabel(self.widget1)
        self.card2_hand2.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"background-color: rgb(0, 0, 98);")
        self.card2_hand2.setText("")
        self.card2_hand2.setObjectName("card2_hand2")
        self.horizontalLayout_2.addWidget(self.card2_hand2)
        self.Hand1Box = QtWidgets.QGroupBox(self.centralwidget)
        self.Hand1Box.setGeometry(QtCore.QRect(450, 160, 91, 81))
        self.Hand1Box.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.Hand1Box.setObjectName("Hand1Box")
        self.layoutWidget = QtWidgets.QWidget(self.Hand1Box)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 71, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.card1_hand1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.card1_hand1.setFont(font)
        self.card1_hand1.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"border-color: rgb(170, 0, 0);\n"
"background-color: rgb(0, 0, 98);")
        self.card1_hand1.setWordWrap(False)
        self.card1_hand1.setObjectName("card1_hand1")
        self.horizontalLayout_3.addWidget(self.card1_hand1)
        self.card2_hand1 = QtWidgets.QLabel(self.layoutWidget)
        self.card2_hand1.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"background-color: rgb(0, 0, 98);")
        self.card2_hand1.setObjectName("card2_hand1")
        self.horizontalLayout_3.addWidget(self.card2_hand1)
        self.card2_hand1.raise_()
        self.card1_hand1.raise_()
        self.PokerTableImage.raise_()
        self.SettingsBox.raise_()
        self.ReportBox.raise_()
        self.ActionsBox.raise_()
        self.card1_board.raise_()
        self.card2_board.raise_()
        self.card3_board.raise_()
        self.card4_board.raise_()
        self.card5_board.raise_()
        self.BoardBox.raise_()
        self.Hand2Box.raise_()
        self.Hand1Box.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        MainWindow.insertToolBarBreak(self.toolBar)
        self.actionNew_game = QtWidgets.QAction(MainWindow)
        self.actionNew_game.setObjectName("actionNew_game")
        self.actionSave_report = QtWidgets.QAction(MainWindow)
        self.actionSave_report.setObjectName("actionSave_report")
        self.toolBar.addAction(self.actionNew_game)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave_report)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SettingsBox.setTitle(_translate("MainWindow", "Settings"))
        self.ReportBox.setTitle(_translate("MainWindow", "Report"))
        self.ActionsBox.setTitle(_translate("MainWindow", "Actions"))
        self.PassButton.setText(_translate("MainWindow", "PASS"))
        self.CheckButton.setText(_translate("MainWindow", "CHECK"))
        self.CallButton.setText(_translate("MainWindow", "CALL"))
        self.RaiseButton.setText(_translate("MainWindow", "RAISE"))
        self.RaiseText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Raise value:</span></p></body></html>"))
        self.BoardBox.setTitle(_translate("MainWindow", "BOARD"))
        self.Hand2Box.setTitle(_translate("MainWindow", "HAND 2"))
        self.Hand1Box.setTitle(_translate("MainWindow", "HAND 1"))
        self.card1_hand1.setText(_translate("MainWindow", "A♥"))
        self.card2_hand1.setText(_translate("MainWindow", "K♣ "))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew_game.setText(_translate("MainWindow", "New game"))
        self.actionNew_game.setToolTip(_translate("MainWindow", "This action ends current session and starts new game from the begining"))
        self.actionSave_report.setText(_translate("MainWindow", "Save report"))
        self.actionSave_report.setToolTip(_translate("MainWindow", "This action makes a .txt file with report about current game"))
