# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'poker_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1284, 839)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SettingsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.SettingsBox.setGeometry(QtCore.QRect(90, 520, 291, 191))
        self.SettingsBox.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.SettingsBox.setObjectName("SettingsBox")
        self.BetText_2 = QtWidgets.QLabel(self.SettingsBox)
        self.BetText_2.setGeometry(QtCore.QRect(20, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.BetText_2.setFont(font)
        self.BetText_2.setStyleSheet("font: 900 12pt \"Perpetua Titling MT\";")
        self.BetText_2.setObjectName("BetText_2")
        self.BetText_3 = QtWidgets.QLabel(self.SettingsBox)
        self.BetText_3.setGeometry(QtCore.QRect(20, 130, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.BetText_3.setFont(font)
        self.BetText_3.setStyleSheet("font: 900 12pt \"Perpetua Titling MT\";")
        self.BetText_3.setObjectName("BetText_3")
        self.BetText_4 = QtWidgets.QLabel(self.SettingsBox)
        self.BetText_4.setGeometry(QtCore.QRect(20, 80, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.BetText_4.setFont(font)
        self.BetText_4.setStyleSheet("font: 900 12pt \"Perpetua Titling MT\";")
        self.BetText_4.setObjectName("BetText_4")
        self.PlayerScoreValue = QtWidgets.QLabel(self.SettingsBox)
        self.PlayerScoreValue.setGeometry(QtCore.QRect(200, 30, 61, 31))
        self.PlayerScoreValue.setStyleSheet("border: 2px solid grey;\n"
"background-color: rgb(232, 232, 232);")
        self.PlayerScoreValue.setText("")
        self.PlayerScoreValue.setObjectName("PlayerScoreValue")
        self.BetValue_3 = QtWidgets.QLabel(self.SettingsBox)
        self.BetValue_3.setGeometry(QtCore.QRect(200, 80, 61, 31))
        self.BetValue_3.setStyleSheet("border: 2px solid grey;\n"
"background-color: rgb(232, 232, 232);")
        self.BetValue_3.setText("")
        self.BetValue_3.setObjectName("BetValue_3")
        self.BetValue_4 = QtWidgets.QLabel(self.SettingsBox)
        self.BetValue_4.setGeometry(QtCore.QRect(200, 130, 61, 31))
        self.BetValue_4.setStyleSheet("border: 2px solid grey;\n"
"background-color: rgb(232, 232, 232);")
        self.BetValue_4.setText("")
        self.BetValue_4.setObjectName("BetValue_4")
        self.BetText_2.raise_()
        self.BetText_3.raise_()
        self.BetText_4.raise_()
        self.PlayerScoreValue.raise_()
        self.BetValue_3.raise_()
        self.BetValue_4.raise_()
        self.ActionsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ActionsBox.setGeometry(QtCore.QRect(470, 570, 351, 141))
        self.ActionsBox.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.ActionsBox.setObjectName("ActionsBox")
        self.PassButton = QtWidgets.QPushButton(self.ActionsBox)
        self.PassButton.setGeometry(QtCore.QRect(30, 50, 75, 51))
        self.PassButton.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"font: 900 12pt \"Perpetua Titling MT\";\n"
"color: rgb(0, 0, 0);")
        self.PassButton.setObjectName("PassButton")
        self.CallButton = QtWidgets.QPushButton(self.ActionsBox)
        self.CallButton.setGeometry(QtCore.QRect(140, 50, 75, 51))
        self.CallButton.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"font: 900 12pt \"Perpetua Titling MT\";\n"
"color: rgb(0, 0, 0);")
        self.CallButton.setObjectName("CallButton")
        self.RaiseButton = QtWidgets.QPushButton(self.ActionsBox)
        self.RaiseButton.setGeometry(QtCore.QRect(250, 50, 71, 51))
        self.RaiseButton.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"font: 900 12pt \"Perpetua Titling MT\";\n"
"color: rgb(0, 0, 0);")
        self.RaiseButton.setObjectName("RaiseButton")
        self.PokerTableImage = QtWidgets.QLabel(self.centralwidget)
        self.PokerTableImage.setGeometry(QtCore.QRect(150, -20, 1001, 871))
        self.PokerTableImage.setText("")
        self.PokerTableImage.setPixmap(QtGui.QPixmap("../images/Poker_table_picture_full.png"))
        self.PokerTableImage.setObjectName("PokerTableImage")
        self.BoardBox = QtWidgets.QGroupBox(self.centralwidget)
        self.BoardBox.setGeometry(QtCore.QRect(540, 230, 211, 81))
        self.BoardBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(9, 70, 10);")
        self.BoardBox.setObjectName("BoardBox")
        self.layoutWidget = QtWidgets.QWidget(self.BoardBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 191, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.card1_board = QtWidgets.QLabel(self.layoutWidget)
        self.card1_board.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"background-color: rgb(0, 0, 98);")
        self.card1_board.setText("")
        self.card1_board.setObjectName("card1_board")
        self.horizontalLayout.addWidget(self.card1_board)
        self.card2_board = QtWidgets.QLabel(self.layoutWidget)
        self.card2_board.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"background-color: rgb(0, 0, 98);")
        self.card2_board.setText("")
        self.card2_board.setObjectName("card2_board")
        self.horizontalLayout.addWidget(self.card2_board)
        self.card3_board = QtWidgets.QLabel(self.layoutWidget)
        self.card3_board.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"background-color: rgb(0, 0, 98);")
        self.card3_board.setText("")
        self.card3_board.setObjectName("card3_board")
        self.horizontalLayout.addWidget(self.card3_board)
        self.card4_board = QtWidgets.QLabel(self.layoutWidget)
        self.card4_board.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"background-color: rgb(0, 0, 98);")
        self.card4_board.setText("")
        self.card4_board.setObjectName("card4_board")
        self.horizontalLayout.addWidget(self.card4_board)
        self.card5_board = QtWidgets.QLabel(self.layoutWidget)
        self.card5_board.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"background-color: rgb(0, 0, 98);")
        self.card5_board.setText("")
        self.card5_board.setObjectName("card5_board")
        self.horizontalLayout.addWidget(self.card5_board)
        self.Hand2Box = QtWidgets.QGroupBox(self.centralwidget)
        self.Hand2Box.setGeometry(QtCore.QRect(600, 140, 91, 81))
        self.Hand2Box.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(9, 70, 10);")
        self.Hand2Box.setObjectName("Hand2Box")
        self.layoutWidget1 = QtWidgets.QWidget(self.Hand2Box)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 71, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.card1_hand2 = QtWidgets.QLabel(self.layoutWidget1)
        self.card1_hand2.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"background-color: rgb(0, 0, 98);")
        self.card1_hand2.setText("")
        self.card1_hand2.setObjectName("card1_hand2")
        self.horizontalLayout_2.addWidget(self.card1_hand2)
        self.card2_hand2 = QtWidgets.QLabel(self.layoutWidget1)
        self.card2_hand2.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"background-color: rgb(0, 0, 98);")
        self.card2_hand2.setText("")
        self.card2_hand2.setObjectName("card2_hand2")
        self.horizontalLayout_2.addWidget(self.card2_hand2)
        self.Hand1Box = QtWidgets.QGroupBox(self.centralwidget)
        self.Hand1Box.setGeometry(QtCore.QRect(600, 330, 91, 81))
        self.Hand1Box.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(9, 70, 10);")
        self.Hand1Box.setObjectName("Hand1Box")
        self.layoutWidget2 = QtWidgets.QWidget(self.Hand1Box)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 71, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.card1_hand1 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.card1_hand1.setFont(font)
        self.card1_hand1.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"border-color: rgb(170, 0, 0);\n"
"background-color: rgb(0, 0, 98);")
        self.card1_hand1.setWordWrap(False)
        self.card1_hand1.setObjectName("card1_hand1")
        self.horizontalLayout_3.addWidget(self.card1_hand1)
        self.card2_hand1 = QtWidgets.QLabel(self.layoutWidget2)
        self.card2_hand1.setStyleSheet("font: 75 12pt \"Perpetua Titling MT\";\n"
"background-color: rgb(0, 0, 98);")
        self.card2_hand1.setObjectName("card2_hand1")
        self.horizontalLayout_3.addWidget(self.card2_hand1)
        self.card2_hand1.raise_()
        self.card1_hand1.raise_()
        self.layoutWidget.raise_()
        self.Hand2Box.raise_()
        self.ReportBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ReportBox.setGeometry(QtCore.QRect(910, 520, 271, 191))
        self.ReportBox.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.ReportBox.setObjectName("ReportBox")
        self.ReportText = QtWidgets.QListView(self.ReportBox)
        self.ReportText.setGeometry(QtCore.QRect(30, 30, 211, 131))
        self.ReportText.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.ReportText.setObjectName("ReportText")
        self.PokerTableImage.raise_()
        self.SettingsBox.raise_()
        self.ActionsBox.raise_()
        self.BoardBox.raise_()
        self.Hand2Box.raise_()
        self.Hand1Box.raise_()
        self.ReportBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew_game = QtWidgets.QAction(MainWindow)
        self.actionNew_game.setObjectName("actionNew_game")
        self.actionSave_report = QtWidgets.QAction(MainWindow)
        self.actionSave_report.setObjectName("actionSave_report")
        self.toolBar.addAction(self.actionNew_game)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave_report)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SettingsBox.setTitle(_translate("MainWindow", "Game"))
        self.BetText_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" text-decoration: underline; color:#ffffff;\">PLAYER SCORE:</span></p></body></html>"))
        self.BetText_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" text-decoration: underline; color:#ffffff;\">BET value:</span></p></body></html>"))
        self.BetText_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" text-decoration: underline; color:#ffffff;\">OPPONENT SCORE:</span></p></body></html>"))
        self.ActionsBox.setTitle(_translate("MainWindow", "Actions"))
        self.PassButton.setText(_translate("MainWindow", "PASS"))
        self.CallButton.setText(_translate("MainWindow", "CALL"))
        self.RaiseButton.setText(_translate("MainWindow", "RAISE"))
        self.BoardBox.setTitle(_translate("MainWindow", "BOARD"))
        self.Hand2Box.setTitle(_translate("MainWindow", "HAND 2"))
        self.Hand1Box.setTitle(_translate("MainWindow", "HAND 1"))
        self.card1_hand1.setText(_translate("MainWindow", "A♥"))
        self.card2_hand1.setText(_translate("MainWindow", "K♣ "))
        self.ReportBox.setTitle(_translate("MainWindow", "Report"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew_game.setText(_translate("MainWindow", "New game"))
        self.actionNew_game.setToolTip(_translate("MainWindow", "This action ends current session and starts new game from the begining"))
        self.actionSave_report.setText(_translate("MainWindow", "Save report"))
        self.actionSave_report.setToolTip(_translate("MainWindow", "This action makes a .txt file with report about current game"))
